version: '3.8'

services:
  api:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 stocks_products.wsgi
    volumes:
      - ./products/:/usr/src/products/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    image: postgres:11.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: pg_user
      POSTGRES_PASSWORD: pg_password
      POSTGRES_DB: pg_db
    ports:
      - 5432:5432

  nginx:
    build: ./nginx
    depends_on:
      - api
    ports:
      - 8080:80

volumes:
  postgres_data: